//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abuelo_Biblioteca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abuelo_Biblioteca()
        {
            this.Padre_Biblioteca = new HashSet<Padre_Biblioteca>();
        }
    
        public int IdAbuelo { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdgraficoFK { get; set; }
    
        public virtual Grafico_Biblioteca Grafico_Biblioteca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Padre_Biblioteca> Padre_Biblioteca { get; set; }
    }
}
