//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbueloCirculosVarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbueloCirculosVarios()
        {
            this.PapaCirculosVarios = new HashSet<PapaCirculosVarios>();
        }
    
        public int IdAbuelo { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> IdGraficoFK { get; set; }
        public string Color { get; set; }
        public Nullable<int> Montonominal { get; set; }
        public Nullable<int> MontoPercapita { get; set; }
        public Nullable<int> sizePercapita { get; set; }
        public Nullable<int> Size { get; set; }
    
        public virtual GraficoCircularesVarios GraficoCircularesVarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapaCirculosVarios> PapaCirculosVarios { get; set; }
    }
}
