//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMunicipalidad
    {
        public int IdAppMunicipalidad { get; set; }
        public string NombreComuna { get; set; }
        public Nullable<int> AEducacion { get; set; }
        public Nullable<int> ASalud { get; set; }
        public Nullable<int> AInterno { get; set; }
        public Nullable<int> ACultural { get; set; }
        public Nullable<int> AComunidad { get; set; }
        public Nullable<int> BEducacion { get; set; }
        public Nullable<int> BSalud { get; set; }
        public Nullable<int> BInterno { get; set; }
        public Nullable<int> BCultural { get; set; }
        public Nullable<int> BComunidad { get; set; }
        public Nullable<int> Poblacion { get; set; }
        public string Alcalde { get; set; }
        public string Partido { get; set; }
        public Nullable<int> Votos { get; set; }
        public Nullable<int> Reelecciones { get; set; }
        public Nullable<int> PobrezaPorciento { get; set; }
        public Nullable<int> Distancia { get; set; }
    }
}
