//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulos_Grafico_d3Object_Bubble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Circulos_Grafico_d3Object_Bubble()
        {
            this.SubCirculos_Grafico_d3Object_Bubble = new HashSet<SubCirculos_Grafico_d3Object_Bubble>();
        }
    
        public int IdCirculo { get; set; }
        public string Titulo { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<int> valorPeso { get; set; }
        public Nullable<double> ValorPorcentaje { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdGraficoFK { get; set; }
        public string Tipo { get; set; }
        public string Texto { get; set; }
        public string Tooltip { get; set; }
        public string Tooltip2 { get; set; }
    
        public virtual Grafico_d3Object_Bubble Grafico_d3Object_Bubble { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCirculos_Grafico_d3Object_Bubble> SubCirculos_Grafico_d3Object_Bubble { get; set; }
    }
}
