//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosApp2
    {
        public int IdDatosApp2 { get; set; }
        public string Categoria { get; set; }
        public string subcategoria { get; set; }
        public Nullable<double> valorCategoria { get; set; }
        public Nullable<double> valorsubcategoria { get; set; }
    }
}
