//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosAPP
    {
        public int IdDato { get; set; }
        public Nullable<int> Ingreso { get; set; }
        public Nullable<bool> Genero { get; set; }
        public Nullable<decimal> Personaje { get; set; }
        public Nullable<decimal> Alcoholicas { get; set; }
        public Nullable<decimal> Analcoholicas { get; set; }
        public Nullable<decimal> Tabaco { get; set; }
        public Nullable<decimal> Combustitble { get; set; }
        public Nullable<decimal> ImpRenta { get; set; }
        public Nullable<decimal> TotalImpuesto { get; set; }
    }
}
