//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        public int IdEncuesta { get; set; }
        public Nullable<int> Pregunta1 { get; set; }
        public Nullable<int> Pregunta2 { get; set; }
        public Nullable<int> Pregunta3 { get; set; }
        public Nullable<int> Pregunta4 { get; set; }
        public Nullable<int> Pregunta5 { get; set; }
        public Nullable<int> Pregunta6 { get; set; }
        public string Pregunta7 { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
