//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedSocial2
    {
        public int IdFeedSocial { get; set; }
        public string Otros { get; set; }
        public string Ip { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdSeccionesFK { get; set; }
    
        public virtual Secciones Secciones { get; set; }
    }
}
