//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hijo_Grafico_Timeline
    {
        public int IdDato { get; set; }
        public string Url { get; set; }
        public string Caption { get; set; }
        public string Headline { get; set; }
        public string Texto { get; set; }
        public string Credito { get; set; }
        public string Monthh { get; set; }
        public string Dayy { get; set; }
        public string Yearr { get; set; }
        public Nullable<int> IdPadreFK { get; set; }
    
        public virtual Padre_Grafico_Timeline Padre_Grafico_Timeline { get; set; }
    }
}
