//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hijo_Biblioteca
    {
        public int IdHijo { get; set; }
        public string Nombre { get; set; }
        public string Autores { get; set; }
        public string Institucion { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdPadreFK { get; set; }
        public string Url { get; set; }
        public Nullable<int> Ano { get; set; }
    
        public virtual Padre_Biblioteca Padre_Biblioteca { get; set; }
    }
}
