//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HijoLineasSeparadas
    {
        public int IdHijo { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<double> MontoCapitalAprobado { get; set; }
        public Nullable<double> MontoCapitalVigente { get; set; }
        public Nullable<double> MontoCorrienteAprobado { get; set; }
        public Nullable<double> MontoCorrienteVigente { get; set; }
        public Nullable<int> IdPadreFK { get; set; }
    
        public virtual PadreLineasSeparados PadreLineasSeparados { get; set; }
    }
}
