//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicadores
    {
        public int IdIndicadores { get; set; }
        public string Nombre { get; set; }
        public string Unidadmedida { get; set; }
        public string Valor { get; set; }
        public string Nota { get; set; }
        public Nullable<decimal> TipoI { get; set; }
        public Nullable<decimal> IndicadorI { get; set; }
        public Nullable<decimal> UnidadI { get; set; }
    }
}
