//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas_Grafico_Plotly_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lineas_Grafico_Plotly_Line()
        {
            this.Datos_Grafico_Plotly_Line = new HashSet<Datos_Grafico_Plotly_Line>();
        }
    
        public int IdLinea { get; set; }
        public string Titulo { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdGraficoFK { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Datos_Grafico_Plotly_Line> Datos_Grafico_Plotly_Line { get; set; }
        public virtual Grafico_Plotly_Line Grafico_Plotly_Line { get; set; }
    }
}
