//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas_Plotly_Listbox
    {
        public int IdLinea { get; set; }
        public string Titulo { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<int> IdGraficoFK { get; set; }
        public Nullable<int> IdSubCategoriaFK { get; set; }
        public Nullable<int> ano1 { get; set; }
        public Nullable<int> ano2 { get; set; }
        public Nullable<int> ano3 { get; set; }
        public Nullable<int> ano4 { get; set; }
        public Nullable<int> ano5 { get; set; }
        public Nullable<int> ano6 { get; set; }
        public Nullable<int> ano7 { get; set; }
        public Nullable<int> ano8 { get; set; }
        public Nullable<int> ano9 { get; set; }
    
        public virtual Grafico_Plotly_Listbox Grafico_Plotly_Listbox { get; set; }
        public virtual SubCategoria_Plotly_Listbox SubCategoria_Plotly_Listbox { get; set; }
    }
}
