//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class base999Entities : DbContext
    {
        public base999Entities()
            : base("name=base999Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abuelo_Biblioteca> Abuelo_Biblioteca { get; set; }
        public virtual DbSet<AbueloCirculosVarios> AbueloCirculosVarios { get; set; }
        public virtual DbSet<AplicacionQuiz> AplicacionQuiz { get; set; }
        public virtual DbSet<AppMunicipalidad> AppMunicipalidad { get; set; }
        public virtual DbSet<Area_googleChart_Area> Area_googleChart_Area { get; set; }
        public virtual DbSet<Barra_amChart_HorizontalBar> Barra_amChart_HorizontalBar { get; set; }
        public virtual DbSet<Categoria_Plotly_Listbox> Categoria_Plotly_Listbox { get; set; }
        public virtual DbSet<Circulos_Grafico_d3Object_Bubble> Circulos_Grafico_d3Object_Bubble { get; set; }
        public virtual DbSet<Cuadrados_d3Object_TreeMap> Cuadrados_d3Object_TreeMap { get; set; }
        public virtual DbSet<Datos_googleChart_Area> Datos_googleChart_Area { get; set; }
        public virtual DbSet<Datos_googleChart_Line> Datos_googleChart_Line { get; set; }
        public virtual DbSet<Datos_Grafico_Plotly_Line> Datos_Grafico_Plotly_Line { get; set; }
        public virtual DbSet<DatosAPP> DatosAPP { get; set; }
        public virtual DbSet<DatosApp2> DatosApp2 { get; set; }
        public virtual DbSet<DatosdupliCirculosVarios> DatosdupliCirculosVarios { get; set; }
        public virtual DbSet<DatosSoloUnoCirculosVarios> DatosSoloUnoCirculosVarios { get; set; }
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<Estudio> Estudio { get; set; }
        public virtual DbSet<EstudioCategoria> EstudioCategoria { get; set; }
        public virtual DbSet<FeedSocial> FeedSocial { get; set; }
        public virtual DbSet<FeedSocial2> FeedSocial2 { get; set; }
        public virtual DbSet<Formulario> Formulario { get; set; }
        public virtual DbSet<Grafico_amChart_HorizontalBar> Grafico_amChart_HorizontalBar { get; set; }
        public virtual DbSet<Grafico_Biblioteca> Grafico_Biblioteca { get; set; }
        public virtual DbSet<Grafico_d3Object_Bubble> Grafico_d3Object_Bubble { get; set; }
        public virtual DbSet<Grafico_d3Object_TreeMap> Grafico_d3Object_TreeMap { get; set; }
        public virtual DbSet<Grafico_googleChart_Area> Grafico_googleChart_Area { get; set; }
        public virtual DbSet<Grafico_googleChart_Line> Grafico_googleChart_Line { get; set; }
        public virtual DbSet<Grafico_googleChart_Pie> Grafico_googleChart_Pie { get; set; }
        public virtual DbSet<Grafico_Plotly_Line> Grafico_Plotly_Line { get; set; }
        public virtual DbSet<Grafico_Plotly_Listbox> Grafico_Plotly_Listbox { get; set; }
        public virtual DbSet<Grafico_Timeline> Grafico_Timeline { get; set; }
        public virtual DbSet<GraficoCircularesVarios> GraficoCircularesVarios { get; set; }
        public virtual DbSet<GraficoLineasSeparadas> GraficoLineasSeparadas { get; set; }
        public virtual DbSet<Hijo_Biblioteca> Hijo_Biblioteca { get; set; }
        public virtual DbSet<Hijo_Grafico_Timeline> Hijo_Grafico_Timeline { get; set; }
        public virtual DbSet<HijoCirculosVarios> HijoCirculosVarios { get; set; }
        public virtual DbSet<HijoLineasSeparadas> HijoLineasSeparadas { get; set; }
        public virtual DbSet<Indicadores> Indicadores { get; set; }
        public virtual DbSet<Json> Json { get; set; }
        public virtual DbSet<JsonVistas> JsonVistas { get; set; }
        public virtual DbSet<Lineas_googleChart_Line> Lineas_googleChart_Line { get; set; }
        public virtual DbSet<Lineas_Grafico_Plotly_Line> Lineas_Grafico_Plotly_Line { get; set; }
        public virtual DbSet<Lineas_Plotly_Listbox> Lineas_Plotly_Listbox { get; set; }
        public virtual DbSet<nivel1> nivel1 { get; set; }
        public virtual DbSet<nivel11> nivel11 { get; set; }
        public virtual DbSet<nivel2> nivel2 { get; set; }
        public virtual DbSet<nivel22> nivel22 { get; set; }
        public virtual DbSet<nivel3> nivel3 { get; set; }
        public virtual DbSet<nivel4> nivel4 { get; set; }
        public virtual DbSet<nivel5> nivel5 { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Padre_Biblioteca> Padre_Biblioteca { get; set; }
        public virtual DbSet<Padre_Grafico_Timeline> Padre_Grafico_Timeline { get; set; }
        public virtual DbSet<PadreLineasSeparados> PadreLineasSeparados { get; set; }
        public virtual DbSet<PapaCirculosVarios> PapaCirculosVarios { get; set; }
        public virtual DbSet<PreguntasFrecuentes> PreguntasFrecuentes { get; set; }
        public virtual DbSet<RegistroAppMunicipal> RegistroAppMunicipal { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
        public virtual DbSet<SubCategoria_Plotly_Listbox> SubCategoria_Plotly_Listbox { get; set; }
        public virtual DbSet<SubCirculos_Grafico_d3Object_Bubble> SubCirculos_Grafico_d3Object_Bubble { get; set; }
        public virtual DbSet<SubCuadrados_d3Object_TreeMap> SubCuadrados_d3Object_TreeMap { get; set; }
        public virtual DbSet<Tabla_amChart_HorizontalBar> Tabla_amChart_HorizontalBar { get; set; }
        public virtual DbSet<Torta_Grafico_googleChart_Pie> Torta_Grafico_googleChart_Pie { get; set; }
        public virtual DbSet<view_ListaSeccionAplicacion> view_ListaSeccionAplicacion { get; set; }
        public virtual DbSet<view_ListaSeccionEtiqueta> view_ListaSeccionEtiqueta { get; set; }
        public virtual DbSet<view_ListaSeccionNoticia> view_ListaSeccionNoticia { get; set; }
        public virtual DbSet<view_ListaSeccionPublicacion> view_ListaSeccionPublicacion { get; set; }
        public virtual DbSet<view_ListaSeccionVisualizacion> view_ListaSeccionVisualizacion { get; set; }
    }
}
