//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nivel3()
        {
            this.nivel4 = new HashSet<nivel4>();
        }
    
        public int IdNivel3 { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<bool> Tipo { get; set; }
        public Nullable<int> Fk_IdNivel2 { get; set; }
        public Nullable<int> Valor2 { get; set; }
        public string PorcentajeGastadoAlPapa { get; set; }
        public string PorcentajePresupeustadoAlPapa { get; set; }
        public string Descripcion { get; set; }
    
        public virtual nivel2 nivel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nivel4> nivel4 { get; set; }
    }
}
