//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel22
    {
        public int IdNivel22 { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<bool> Tipo { get; set; }
        public Nullable<int> Fk_IdNivel11 { get; set; }
        public Nullable<int> Valor2 { get; set; }
        public string PorcentajeGastadoAlPapa { get; set; }
        public string PorcentajePresupeustadoAlPapa { get; set; }
        public string Descripcion { get; set; }
    
        public virtual nivel11 nivel11 { get; set; }
    }
}
