//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel11
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nivel11()
        {
            this.nivel22 = new HashSet<nivel22>();
        }
    
        public int IdNivel11 { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<bool> Tipo { get; set; }
        public Nullable<int> Valor2 { get; set; }
        public string PorcentajeGastadoAlPapa { get; set; }
        public string PorcentajePresupeustadoAlPapa { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nivel22> nivel22 { get; set; }
    }
}
