//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padre_Grafico_Timeline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Padre_Grafico_Timeline()
        {
            this.Hijo_Grafico_Timeline = new HashSet<Hijo_Grafico_Timeline>();
        }
    
        public int IdLinea { get; set; }
        public string Url { get; set; }
        public string Caption { get; set; }
        public string Headline { get; set; }
        public string Texto { get; set; }
        public string Credito { get; set; }
        public Nullable<int> IdGraficoFK { get; set; }
    
        public virtual Grafico_Timeline Grafico_Timeline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hijo_Grafico_Timeline> Hijo_Grafico_Timeline { get; set; }
    }
}
