//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padre_Biblioteca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Padre_Biblioteca()
        {
            this.Hijo_Biblioteca = new HashSet<Hijo_Biblioteca>();
        }
    
        public int IdPadre { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdAbueloFK { get; set; }
    
        public virtual Abuelo_Biblioteca Abuelo_Biblioteca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hijo_Biblioteca> Hijo_Biblioteca { get; set; }
    }
}
