//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PadreLineasSeparados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PadreLineasSeparados()
        {
            this.HijoLineasSeparadas = new HashSet<HijoLineasSeparadas>();
        }
    
        public int IdPadre { get; set; }
        public string Titulo { get; set; }
        public string ColorCorriente { get; set; }
        public string ColorCapital { get; set; }
        public Nullable<int> IdGraficoFK { get; set; }
    
        public virtual GraficoLineasSeparadas GraficoLineasSeparadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HijoLineasSeparadas> HijoLineasSeparadas { get; set; }
    }
}
