//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAppMunicipal
    {
        public int IdRegistroAppMunicipal { get; set; }
        public Nullable<int> Educacion { get; set; }
        public Nullable<int> Salud { get; set; }
        public Nullable<int> Interno { get; set; }
        public Nullable<int> Cultural { get; set; }
        public Nullable<int> Comunidad { get; set; }
        public string NombreComuna { get; set; }
        public string Ip { get; set; }
    }
}
