//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Secciones()
        {
            this.FeedSocial = new HashSet<FeedSocial>();
            this.FeedSocial2 = new HashSet<FeedSocial2>();
        }
    
        public int IdSecciones { get; set; }
        public bool Retroalimentacion { get; set; }
        public string Archivo { get; set; }
        public string TituloPregunta { get; set; }
        public string TituloRedes { get; set; }
        public string Resumen { get; set; }
        public string ImagenUrl { get; set; }
        public string UrlDireccion { get; set; }
        public string TituloInterna { get; set; }
        public string SubTitulo { get; set; }
        public string DescripcionSuperior { get; set; }
        public string DescripcionCentral { get; set; }
        public string DescripcionInferior { get; set; }
        public string DescripcionScript { get; set; }
        public Nullable<decimal> Tipo { get; set; }
        public string Etiquetas { get; set; }
        public Nullable<System.DateTime> Fecha2 { get; set; }
        public Nullable<bool> Destacar { get; set; }
        public Nullable<int> Megusta { get; set; }
        public string autor { get; set; }
        public string TipoPublicacion { get; set; }
        public string Recomendado { get; set; }
        public string dataset { get; set; }
        public string DescripcionCentralM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedSocial> FeedSocial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedSocial2> FeedSocial2 { get; set; }
    }
}
