//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCirculos_Grafico_d3Object_Bubble
    {
        public int IdDato { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<int> valorPeso { get; set; }
        public Nullable<double> ValorPorcentaje { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdCirculoFK { get; set; }
        public string Titulo { get; set; }
        public string Tipo { get; set; }
        public string Texto { get; set; }
        public string Tooltip { get; set; }
        public string Tooltip2 { get; set; }
    
        public virtual Circulos_Grafico_d3Object_Bubble Circulos_Grafico_d3Object_Bubble { get; set; }
    }
}
