//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCuadrados_d3Object_TreeMap
    {
        public int IdDato { get; set; }
        public Nullable<int> valorPercapita { get; set; }
        public Nullable<double> ValorPorcentaje { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdCirculoFK { get; set; }
        public string IdRegion { get; set; }
        public Nullable<int> valorNominal { get; set; }
        public string Tipo { get; set; }
        public string Titulo { get; set; }
    
        public virtual Cuadrados_d3Object_TreeMap Cuadrados_d3Object_TreeMap { get; set; }
    }
}
