//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torta_Grafico_googleChart_Pie
    {
        public int IdTorta { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Valor { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdGraficoFK { get; set; }
    
        public virtual Grafico_googleChart_Pie Grafico_googleChart_Pie { get; set; }
    }
}
