//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALObservatorioNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ListaSeccionEtiqueta
    {
        public int ID { get; set; }
        public string TituloPregunta { get; set; }
        public string Resumen { get; set; }
        public string UrlDireccion { get; set; }
        public string Fecha { get; set; }
        public Nullable<System.DateTime> FechaFecha { get; set; }
        public Nullable<decimal> Tipo { get; set; }
        public string ImagenUrl { get; set; }
        public string Etiquetas { get; set; }
    }
}
